security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'


    providers:
        personne_login_provider:
            entity:
                class: App\Entity\PersonneLogin
                property: login

    firewalls:
        dev:
            pattern: ^/infirmiere/login
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/
            stateless: true
            provider: personne_login_provider
            jwt: ~ 

        main:
            lazy: true
            provider: personne_login_provider
            logout:
                path: api_logout
                invalidate_session: false

    access_control:
        - { path: ^/infirmiere/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }