security:
    password_hashers:
        App\Entity\PersonneLogin:
            algorithm: auto
            migrate_from: [md5, sha256]

    providers:
        personne_login_provider:
            entity:
                class: App\Entity\PersonneLogin
                property: login


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: personne_login_provider
            custom_authenticator: App\Security\LoginAuthenticator
            entry_point: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: redirect_after_login

    access_control:
        # Public
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/infirmiere/login, roles: PUBLIC_ACCESS }
        - { path: ^/patient/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/change-password, roles: PUBLIC_ACCESS }

        # Admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Infirmiere
        - { path: ^/infirmiere, roles: [ROLE_INFIRMIERE, ROLE_ADMIN] }

        # Patient
        - { path: ^/patient, roles: [ROLE_PATIENT, ROLE_ADMIN] }

        - { path: ^/patient/mon-compte, roles: ROLE_PATIENT }
        - { path: ^/patient/\d+/index, roles: ROLE_ADMIN }
        - { path: ^/patient/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/patient/\d+/delete, roles: ROLE_ADMIN }

        - { path: ^/infirmiere/admin/\d+/index, roles: ROLE_ADMIN }
        - { path: ^/infirmiere/admin/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/infirmiere/admin/\d+/delete, roles: ROLE_ADMIN }

        - { path: ^/soins/admin/\d+/index, roles: ROLE_ADMIN }
        - { path: ^/soins/admin/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/soins/admin/\d+/delete, roles: ROLE_ADMIN }

